### ISSUE TITLE
提示 加载 拖放支持库 2.0 失败

### ISSUE THREAD

**Issue by yjd** [OpenEpl/TextECode#8]
今天要搜索常量里的文本内容，想到有这个项目。第一次使用。下载测试。请作者看看
错误如下：
```
fail: OpenEpl.TextECode.TextECodeGenerator[0]
      加载支持库 拖放支持库 (FileName=edroptarget, GUID={9DA96BF9CEBD45c5BFCF94CBE61671F5}) v2.0 失败
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenEpl.TextECode.Internal.FormInfoGenerator..ctor(FormInfo formInfo, IdToNameMap idToNameMap) in D:\a\TextECode\TextECode\TextECode\Internal\FormInfoGenerator.cs:line 58
   at OpenEpl.TextECode.TextECodeGenerator.HandleForm(CodeFolderInfo folderInfo, FormInfo elem) in D:\a\TextECode\TextECode\TextECode\TextECodeGenerator.cs:line 440
   at OpenEpl.TextECode.TextECodeGenerator.HandleForms(CodeFolderInfo folderInfo, IEnumerable`1 classes) in D:\a\TextECode\TextECode\TextECode\TextECodeGenerator.cs:line 429
   at OpenEpl.TextECode.TextECodeGenerator.Generate() in D:\a\TextECode\TextECode\TextECode\TextECodeGenerator.cs:line 216
   at OpenEpl.TextECodeCLI.GenerateCmd.Run(ILoggerFactory loggerFactory) in D:\a\TextECode\TextECode\TextECodeCLI\Program.cs:line 61
   at OpenEpl.TextECodeCLI.Program.<>c__DisplayClass1_0.<Main>b__2(Object options) in D:\a\TextECode\TextECode\TextECodeCLI\Program.cs:line 239
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at OpenEpl.TextECodeCLI.Program.Main(String[] args) in D:\a\TextECode\TextECode\TextECodeCLI\Program.cs:line 232
```

**Comment by ArcticLampyrid** [comment]
是否能提供相关*.e源文件和支持库？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: yjd ***@***.***>
发送时间: Thursday, November 9, 2023 10:07:01 AM
收件人: OpenEpl/TextECode ***@***.***>
抄送: Subscribed ***@***.***>
主题: [OpenEpl/TextECode] 提示 加载 拖放支持库 2.0 失败 (Issue #8)


今天要搜索常量里的文本内容，想到有这个项目。第一次使用。下载测试。请作者看看
错误如下：

fail: OpenEpl.TextECode.TextECodeGenerator[0]
      加载支持库 拖放支持库 (FileName=edroptarget, GUID={9DA96BF9CEBD45c5BFCF94CBE61671F5}) v2.0 失败
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenEpl.TextECode.Internal.FormInfoGenerator..ctor(FormInfo formInfo, IdToNameMap idToNameMap) in D:\a\TextECode\TextECode\TextECode\Internal\FormInfoGenerator.cs:line 58
   at OpenEpl.TextECode.TextECodeGenerator.HandleForm(CodeFolderInfo folderInfo, FormInfo elem) in D:\a\TextECode\TextECode\TextECode\TextECodeGenerator.cs:line 440
   at OpenEpl.TextECode.TextECodeGenerator.HandleForms(CodeFolderInfo folderInfo, IEnumerable`1 classes) in D:\a\TextECode\TextECode\TextECode\TextECodeGenerator.cs:line 429
   at OpenEpl.TextECode.TextECodeGenerator.Generate() in D:\a\TextECode\TextECode\TextECode\TextECodeGenerator.cs:line 216
   at OpenEpl.TextECodeCLI.GenerateCmd.Run(ILoggerFactory loggerFactory) in D:\a\TextECode\TextECode\TextECodeCLI\Program.cs:line 61
   at OpenEpl.TextECodeCLI.Program.<>c__DisplayClass1_0.<Main>b__2(Object options) in D:\a\TextECode\TextECode\TextECodeCLI\Program.cs:line 239
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at OpenEpl.TextECodeCLI.Program.Main(String[] args) in D:\a\TextECode\TextECode\TextECodeCLI\Program.cs:line 232


―

**Comment by yjd** [comment]
原文件代码太多了。不过新建一个复现了同样错误。
[拖放对象.zip](https://github.com/OpenEpl/TextECode/files/13317569/default.zip)

**Comment by ArcticLampyrid** [comment]
尝试一下 v0.1.2，如果安装失败的话先手动卸载老版本（AppX的签名有变动）

**Comment by yjd** [comment]
我用的是 TextECode_0.1.2_Portable_x64.zip，测试上面的附件，这次错误不同。
```
TextECode.exe generate test.e test.eproject
08:48:05 fail: OpenEpl.TextECode.TextECodeGenerator[0]
      加载支持库 拖放支持库 (FileName=edroptarget, GUID={9DA96BF9CEBD45c5BFCF94CBE61671F5}) v2.0 失败
08:48:05 fail: OpenEpl.TextECode.Internal.FormInfoGenerator[0]
      未知的窗口数据类型: 拖放支持库.0
```

**Comment by ArcticLampyrid** [comment]
emmm，似乎忘记打包了一些东西，试试 v1.9.3

**Comment by yjd** [comment]
我资源里有个名字为 （通用模板2xlsx）的xlsx格式的文件，生成出来变成 （通用模板2xlsx.zip） 而不是 (通用模板2xlsx.xlsx )
另一个 （通用模板2xls）出来是 （通用模板2xls.xls）倒是正确。
这个是有意改扩展名？
@ArcticLampyrid

**Comment by ArcticLampyrid** [comment]
> 我资源里有个名字为 （通用模板2xlsx）的xlsx格式的文件，生成出来变成 （通用模板2xlsx.zip） 而不是 (通用模板2xlsx.xlsx )
> 另一个 （通用模板2xls）出来是 （通用模板2xls.xls）倒是正确。
> 这个是有意改扩展名？

目前所用的扩展名识别的思路，很难识别并区分新版office格式和zip
